name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 3
      matrix:
        include:
          - module: "Core"
            path: "."
          - module: "Math"
            path: "modules/Math/"
    env:
      COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer Install
        run: composer install --no-interaction

      - name: Create SQLite database
        run: |
          touch database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate:fresh --env=testing

      - name: Run test - ${{ matrix.module }}
        run: php artisan test -c ${{ matrix.path }}/phpunit.xml  --coverage --coverage-clover storage/coverage/coverage_${{ matrix.module }}.xml
        working-directory: ${{ matrix.path }} || ./

      - name: Fix code coverage paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' storage/coverage/coverage_${{ matrix.module }}.xml

      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: storage/coverage/coverage_${{ matrix.module }}.xml
          retention-days: 1


  sonarcloud:
    runs-on: ubuntu-22.04
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download coverages
        uses: actions/download-artifact@v3
        id: download
        with:
          path: build

      - name: Echo download path
        run: echo ${{steps.download.outputs.download-path}}

      - name: Getting report paths for SonarQube
        working-directory: ./build/coverage
        run: |
          coverage=$(find . -type f -name "coverage*.xml" | sed -e 's/^.\//build\/coverage\//' | tr '\n' ',')
          echo "coverageReportPaths=${coverage}" >> $GITHUB_ENV

      - name: Echo coverage report paths env
        run: echo ${{env.coverageReportPaths}}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.php.coverage.reportPaths=${{env.coverageReportPaths}}
