name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test-filter: [
          AuthenticationTest,
          EmailVerificationTest
        ]
    env:
      COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer Install
        run: composer install --no-interaction

      - name: Create SQLite database
        run: |
          touch database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate:fresh --env=testing

      - name: Run test - ${{ matrix.test-filter }}
        run: php artisan test --filter ${{ matrix.test-filter }} --coverage --coverage-clover storage/coverage/coverage_${{ matrix.test-filter }}.xml

      - name: Fix code coverage paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' storage/coverage/coverage_${{ matrix.test-filter }}.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}