name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        operating-system: [ubuntu-20.04]
        php-version: [8.2]
    env:
      COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ssh2, openssl, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: pcov

      - name: Composer Install
        run: composer install --no-interaction

      - name: Create SQLite database
        run: |
          touch database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate:fresh --env=testing

      - name: Run tests
        run: php artisan test
